### ISSUE TITLE
🐛Bug: `$isEmpty` is not triggered when using meilisearch multisearch

### ISSUE THREAD

**Issue by buhodev** [melt-ui/melt-ui#505] opened 2023-09-07 13:46 UTC
**Describe the bug**
`$isEmpty` is not triggered when using async results

**To Reproduce**

1. Go to https://www.meilisearch.com/docs/learn/getting_started/quick_start and follow the steps to install meilisearch locally
2. Start the meilisearch instance with the default master key (`aSampleMasterKey`)
3. Add the following indexes to meilisearch instance:
   - https://github.com/meilisearch/datasets/blob/main/datasets/books/books.json
   - https://github.com/meilisearch/datasets/blob/main/datasets/movies/movies.json
4. Clone https://github.com/buhodev/melt-meilisearch.git
5. Install dependencies
6. Run `dev` command
7. Search for `pwp` in the combobox and see that the `$isEmpty` is not triggered.

**Expected behavior**
`$isEmpty` should be triggered when there are not results

**Comment by huntabyte** [comment] 2023-09-07 15:37
I'm able to reproduce this.

**Comment by huntabyte** [comment] 2023-09-07 16:02
It seems to be registering it empty on the second instance that the results are empty, as in if I type `pwpp`, it appears to work.

**Comment by buhodev** [comment] 2023-09-07 16:06
> It seems to be registering it empty on the second instance that the results are empty, as in if I type `pwpp`, it appears to work.

Hmm, I just tested adding a `p` after typing `pwp` and this doesn't work either on my end

**Comment by TGlide** [comment] 2023-09-07 16:14
This will be fixed by changing the combobox implementation as discussed on discord

**Comment by wesharper** [comment] 2023-09-14 21:05
Can this be closed now that [`$isEmpty` is removed](https://github.com/melt-ui/melt-ui/commit/4da1aa73ac14f5507e35970228978e6982012eb3)?

**Comment by TGlide** [comment] 2023-09-14 22:01
Yes!

**Closed by TGlide** 2023-09-14 22:01 UTC
Labels: bug
