### ISSUE TITLE
[Range Calendar]

### ISSUE THREAD

**Issue by anatolzak** [melt-ui/melt-ui#940] opened 2024-01-31 11:41 UTC
### Describe the bug

If I am not mistaken, there is no way to select the same day as the start and end day in the range calendar.
Is there a way to make that happen?

### Reproduction

Try selecting the same day as the start and end day in the docs, and it will reset the selection.
https://melt-ui.com/docs/builders/range-calendar

https://github.com/melt-ui/melt-ui/assets/53095479/e8a52a75-7fe1-4f4e-8054-aec913a0e708

### System Info

```bash
System:
    OS: macOS 14.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 51.43 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.9.0/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 8.11.0 - /usr/local/bin/pnpm
    bun: 1.0.22 - ~/.bun/bin/bun
  Browsers:
    Chrome: 120.0.6099.109
    Edge: 114.0.1823.82
    Safari: 17.3
```

### Severity

annoyance

**Comment by huntabyte** [comment] 2024-01-31 11:51
Duplicate of #898

**Closed** 2024-01-31 11:51 UTC
Labels: bug
