### ISSUE TITLE
🐛Bug: Dialog is glitching when tapped outside using iOS

### ISSUE THREAD

**Issue by yekta** [melt-ui/melt-ui#26] opened 2023-06-14 15:59 UTC
**Describe the bug**
The dialog component glitches when I tap outside to close it. If I click the “X” to close it, no glitch.

**To Reproduce**
Using iOS 16.5 and iPhone 13 Pro Max:
1. Visit: https://www.melt-ui.com/docs/builders/dialog
2. Open the dialog
3. Tap outside to close it

**Expected behavior**
No glitch, just like with clicking “X”.

**Screenshots**

Uploading RPReplay_Final1686757621.mp4…

**Desktop:**
 - OS: iOS 16.5
 - Browser: Safari

**Smartphone:**
 - Device: iPhone 13 Pro Max
 - OS: iOS 16.5
 - Browser: Safari

**Comment by TGlide** [comment] 2023-06-14 18:15
Closing as duplicate of #27

**Closed by TGlide** 2023-06-14 18:15 UTC
Labels: bug
