### ISSUE TITLE
🐛Bug: Select builder multi-select `defaultSelected` does not allow for default value to be deselected

### ISSUE THREAD

**Issue by mbrandt00** [melt-ui/melt-ui#587] opened 2023-10-03 21:16 UTC
**Describe the bug**
When using `defaultSelected` on a multiselect field (`multiple: true`), the default selected value is not unselectable.  This comes from `CreateSelectProps.` 
**To Reproduce**
Please check [Minimal Repro](https://stackblitz.com/edit/kit-ts-tw-melt-9d9egt?file=src%2Froutes%2F%2Bpage.svelte)

**Expected behavior**
The default value should be unselectable. 
**Screenshots**

https://github.com/melt-ui/melt-ui/assets/91398645/b6e0d8ad-bd77-43b0-b698-1192942ced06

**Additional context**
This is using melt `0.51.0`
@wesharper may be able to take a look.

**Comment by wesharper** [comment] 2023-10-03 21:55
This can be marked as resolved (possibly might want a doc update), but it is a bit of an awkward API that is related to some of my feelings expressed [here](https://github.com/melt-ui/melt-ui/issues/555). I think if the select builder had less reliance on deep equality and instead preferred matching on the `value` attribute, some of these gotchas may come up less.

The issue is that the `toggle` helper does a deep equality check for whatever is in the array. When `melt` adds an `option` object, it implicitly includes all 3 attributes of the `SelectOption` object (i.e. `disabled`, `label`, and `value`). However, if any of these is omitted from the `defaultSelected` array, the deep equality check fails, which prevents the toggle from working as expected.

The API that feels most natural _to me_ in this case would be to just pass an array of simple values and let `melt` manage `option` objects behind the scenes. The use case here is the following:

1. User uses a multi-select input in a form to create a new object.
1. Database stores an array of values (not options objects)
1. User loads the form to edit the object.
1. Client passes in values array from DB directly and melt handles accordingly.

As is, this experience is not possible, and the consumer has to manually convert the array of values to an array of options objects in order to get things working reliably. Once the consuming party knows all of the details, it's a relatively minor annoyance, but the ideal for me would be for melt to create and accept values that can directly interface with the back-end without any "massaging".

**Comment by wesharper** [comment] 2023-10-03 21:59
![Screenshot 2023-10-03 at 3 36 11 PM](https://github.com/melt-ui/melt-ui/assets/13283469/2362c48b-9d36-4d1e-b81b-0a0f0d52b3bb)
Here's some debug logs using the minimal repro as a starting point.

**Comment by wesharper** [comment] 2023-10-03 22:00
I have some ideas for a PR that I can try to get to on Friday, but ultimately it would probably impact lots of folks.

**Comment by wesharper** [comment] 2023-10-03 22:02
A lightweight alternative could be to modify the `defaultSelected` array items into full `option` values with defaults similar to what happens when using the `$option` function.

**Comment by TGlide** [comment] 2023-10-03 22:46
> but the ideal for me would be for melt to create and accept values that can directly interface with the back-end without any "massaging".

I'm not against an alternative! Would be interesting to see.

**Closed** 2023-10-03 22:46 UTC
Labels: bug
