### ISSUE TITLE
🐛Bug: preventScroll prop ignored, scroll locks no matter the option

### ISSUE THREAD

**Issue by EdwardLemayDev** [melt-ui/melt-ui#834] opened 2023-12-19 04:49 UTC
**Describe the bug**
Maybe I misunderstood something, but it seems like the "preventScroll" prop isn't being respected. I have it set to "false" and it still applies the style and data-melt-scroll-lock.

**To Reproduce**
1. Set the "preventScroll" prop to false on the "createMenu" function
2. Click the trigger and watch it lock the scroll anyway

**Expected behavior**
Not to lock the scroll

**Screenshots**
![image](https://github.com/melt-ui/melt-ui/assets/98425916/5b9e46a6-98b6-410b-bbe5-5e13af683397)
![image](https://github.com/melt-ui/melt-ui/assets/98425916/b0951f31-7d8f-4adb-9fad-4c183ac3ffba)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 120.0.6099.110 (Official Build) (64-bit) (cohort: Stable) 

**Additional context**
Love the work you you guys do!

To reproduce using Stackblitz, use this [template](https://stackblitz.com/edit/melt-ui-playground) and modify the `src/routes/+page.svelte` file.

**Comment by alex-k-exe** [comment] 2023-12-25 11:52
I'd like to work on this issue but it would be my first contribution, so could you please give me some advice and confirmation that I should work on it.

**Comment by mcmxcdev** [comment] 2023-12-26 21:23
@huntabyte If you tackle this, we also encountered issues with `preventScroll: true` where it leads to content flickering on mobile devices together with absolute/sticky elements below it. Don't have a repro handy though.

**Comment by huntabyte** [comment] 2023-12-30 19:41
This is a duplicate of #821 so closing this in favor of that one.

**Closed by huntabyte** 2023-12-30 19:41 UTC
Labels: bug
