### ISSUE TITLE
Context Menu doesn't stay open after right click on Safari

### ISSUE THREAD

**Issue by rudiv** [melt-ui/melt-ui#992] opened 2024-02-16 18:41 UTC
### Describe the bug

When right clicking on the context menu trigger in Safari, the menu does not stay open.

You have to right click and drag over the menu for this to stay open.

I know this isn't shadcn, but worked my way down the libraries to figure out where the issue was and it starts with Melt UI. In contrast, [the shadcn component](https://ui.shadcn.com/docs/components/context-menu) works as you'd expect, staying open on right click without moving the mouse.

### Reproduction

https://melt-ui.com/docs/builders/context-menu

### System Info

```bash
System:
    OS: macOS 14.2.1
    CPU: (20) arm64 Apple M1 Ultra
    Memory: 68.21 GB / 128.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - /usr/local/bin/node
    npm: 10.2.3 - /usr/local/bin/npm
  Browsers:
    Safari: 17.2.1
  npmPackages:
    @sveltejs/kit: ^2.5.0 => 2.5.0 
    svelte: ^4.2.10 => 4.2.10
```

### Severity

annoyance

**Comment by TGlide** [comment] 2024-02-26 12:04
Re-opening due to regressions that were fixed by #1016

**Closed** 2024-02-29 20:06 UTC
Labels: bug
