### ISSUE TITLE
Dialog closes on click when inside `shadow-root`

### ISSUE THREAD

**Issue by jramke** [melt-ui/melt-ui#1008] opened 2024-02-23 21:23 UTC
### Describe the bug

Hey,
I'm creating a web extension where I'm using a dialog. I've attached everything to a `shadow root`. 
Therefore, I have to set the portal property of the dialog to either null or an element inside the `shadow root`. However, when the portal property is set, the dialog is closed when clicking inside it. 
I've tried using `null` or an `HTMLElement`, but I'm having trouble getting the latter to work properly in the reproduction. 
I think this issue might be related to the recent portal changes, as everything worked fine a few weeks ago.

### Reproduction

https://stackblitz.com/edit/github-c4hdbt?file=src%2Froutes%2F%2Blayout.svelte

### System Info

```bash
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 9.89 GB / 15.58 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: 8.15.3 - ~/.local/share/pnpm/pnpm
```

### Severity

annoyance

**Comment by TGlide** [comment] 2024-02-23 22:34
Closing as duplicate of #330

**Comment by huntabyte** [comment] 2024-02-24 03:10
Hey there @jramke, you should be able to use the `onOutsideClick` prop to handle this as needed.

Here's an example: https://stackblitz.com/edit/github-c4hdbt-gykuo8?file=src%2Froutes%2F%2Bpage.svelte

The `onOutsideClick` callback is called with the event that triggered an internal "outside click" and if you call `e.preventDefault()`, the dialog won't close!

Hopefully this helps!

**Closed** 2024-02-24 09:02 UTC
Labels: bug
