### ISSUE TITLE
combobox chevronDown/arrow doesn't trigger open

### ISSUE THREAD

**Issue by mustafa0x** [melt-ui/melt-ui#1090] opened 2024-03-14 14:24 UTC
### Describe the bug

clicking on 🔽 doesn't open the combobox

![image](https://github.com/melt-ui/melt-ui/assets/1473102/9b48bdf9-68cd-439a-aa69-22693a758db1)

---

![image](https://github.com/melt-ui/melt-ui/assets/1473102/e56ef42e-b63f-4441-b2f6-832c2657a7f3)

this should probably be a `<button>`

---

<img width="398" alt="image" src="https://github.com/melt-ui/melt-ui/assets/1473102/90640e89-33ef-4eae-866f-0315e429c965">

react aria uses a button

---

related: https://github.com/melt-ui/melt-ui/issues/1024

**Comment by TGlide** [comment] 2024-03-14 14:32
Duplicate of #1024

**Closed by TGlide** 2024-03-14 14:32 UTC
Labels: bug
